load("//tools:protos.bzl", "py_protos")

package(
    default_visibility = ["//visibility:public"],
)

py_protos(
    name = "py_proto_ensemble",
    protos = glob(["object_detection/protos/*.proto"]),
)
