#!/bin/bash
# -*- shell-script -*-

_bsd_="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
_kubectl="$(which kubectl)"

# Once the session is established, run a kubernetes proxy
# from the running machine (perhaps within a tmux session)
# Then we can use the original kubernetes config file
# with only the modification to the server address

# In the LXD version, the proxy is launched inside the 
# first level of LXD container which hosts the
# second level of kubernetes containers
# The kubernetes worker containers hosts docker containers

# Deploying Kubernetes with Juju proves to be a bit more challenging,
# as it requries specific settings of networking and priviliges
# It is best done within another LXD container.
# Most other Juju charms can be deployed easily.
# We setup the bridge interface to expose the LXD containers.

exec "${_kubectl}" --kubeconfig="${_bsd_}/config.lxd-conjure" $@
