---
- name: Create user for OpenStack
  user:
    name: stack
    shell: /bin/bash
    home: /opt/stack
    create_home: yes

- name: Ensure sudo is installed
  package:
    name: sudo
    state: present

- name: Ensure the sudoers.d directory is created
  file:
    path: /etc/sudoers.d
    owner: root
    group: root
    mode: 0750
    state: directory

- name: Make sudoers file support seperate specs if not already replaced
  lineinfile:
    state: present
    dest: /etc/sudoers
    line: '#includedir /etc/sudoers.d'
    insertafter: EOF
    backup: yes
    validate: visudo -cf %s

- name: Set user as the defautl user
  copy:
    content: >-
      stack ALL=(ALL) NOPASSWD: ALL
    dest: /etc/sudoers.d/stack
