---
- name: Create OpenStack required account 'stack'
  include_tasks: create_openstack_user.yml

- name: Clone OpenStack git repository
  become_user: stack
  git:
    repo: https://git.openstack.org/openstack-dev/devstack
    dest: /opt/stack/devstack
    update: yes

- name: Create local config file
  copy:
    content: |
      [[local|localrc]]
      HOST_IP=10.0.0.10
      ADMIN_PASSWORD=amisabc
      DATABASE_PASSWORD=$ADMIN_PASSWORD
      RABBIT_PASSWORD=$ADMIN_PASSWORD
      SERVICE_PASSWORD=$ADMIN_PASSWORD

    dest: /opt/stack/devstack/local.conf

- name: Execute stack
  become_user: stack
  command: ./stack.sh
  args:
    chdir: /opt/stack/devstack
